site_name: 灵韵笔记本
repo_name: chorus-note
repo_url: https://github.com/ckc-lingyun-chorus/chorus-note

theme:
  name: material
  language: 'zh'
  favicon: 'assets/ico/favicon.png'
  icon:
    repo: fontawesome/brands/github
    logo: material/notebook-outline
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.code.copy
  # font: false

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: GoPoux4/notebook
      branch: master
  - git-authors

extra:
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1235523055
      name: 灵韵合唱团的 bilibili 主页
    - icon: fontawesome/brands/weixin
      link: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzU5NDI1Mzg2Mg==&scene=124#wechat_redirect
      name: 灵韵合唱团的微信公众号

extra_css:
  - css/neoteroi-mkdocs.css
  - css/counter.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - index.md
    - 合唱团简介: intro.md